
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM
{

using System;
    using System.Collections.Generic;
    
public partial class vacancy
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public vacancy()
    {

        this.Kompania = new HashSet<Kompania>();

    }


    public int id { get; set; }

    public string name_vacancy { get; set; }

    public Nullable<int> zp { get; set; }

    public string opicanie_vacancy { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Kompania> Kompania { get; set; }

}

}
